configuration:
  - type: APP
    vmLocation: app.vm
  - type: ENTITY
    vmLocation: entity.vm
  - type: ADMIN
    vmLocation: admin_app.vm
  - type: APP_FUNCTION
    vmLocation: app_function.vm
  - type: RELATIONSHIP
    vmLocation: relationship.vm
